const test=require('node:test'); const assert=require('node:assert/strict'); const vm=require('node:vm');
const template=require('./leword-monthly-renewal-template.cjs');
function setup(options={}) {
 const props=new Map([['LEWORD_MONTHLY_RECEIPT_LP-test','hash']]);const calls=[];const triggers=[];
 const sheet=(rows)=>({rows,getDataRange(){return{getValues:()=>this.rows.map(r=>[...r])}},appendRow(row){if(this.failOnce){this.failOnce=false;throw Error('write failed')}this.rows.push([...row])},getRange(row,col,height,width){return{setValue:value=>{if(this.failOnce){this.failOnce=false;throw Error('write failed')}this.rows[row-1][col-1]=value},setValues:values=>{if(this.failOnce){this.failOnce=false;throw Error('write failed')}for(let y=0;y<values.length;y++)for(let x=0;x<values[y].length;x++)this.rows[row-1+y][col-1+x]=values[y][x]}}}});
 const due=new Date(Date.now()-3600000).toISOString();
 const subs=sheet([['key','email','billing','product','name','amount','due','status','retry','code','created','cancelled','last'],['LP-test','buyer@example.test','fake','leword-monthly','LEWORD',19900,due,'active',0,'CODE','', '', '']]);
 const licenses=sheet([['code','platform','type','used','customDays','expiresAt'],['CODE','LEWORD','CUSTOM',true,30,new Date(due)]]);const orders=sheet([['orderId']]);
 const env={Date,JSON,String,Number,isFinite,isNaN,Error,Logger:{log(){}},LockService:{getScriptLock:()=>({tryLock:()=>!options.locked,releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v),deleteProperty:k=>props.delete(k)})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,v)=>Array.from(require('node:crypto').createHash('sha256').update(v).digest()),base64Encode:v=>Buffer.from(v).toString('base64')},ScriptApp:{getProjectTriggers:()=>triggers.map(name=>({getHandlerFunction:()=>name})),newTrigger:name=>({timeBased:()=>({everyDays:()=>({atHour:()=>({create:()=>triggers.push(name)})})})})},getSubscriptionSheet:()=>subs,getSheet:()=>licenses,getOrderSheet:()=>orders,ensureHeaders:s=>s.rows[0],findColumnIndex:(h,k)=>h.indexOf(k)+1,SpreadsheetApp:{flush(){}},getTossSecretKey:()=>'',UrlFetchApp:{fetch(url,opts){calls.push({url,opts});const p=opts.payload?JSON.parse(opts.payload):{orderId:url.split('/').pop()};if(options.timeoutOnce){options.timeoutOnce=false;throw Error('timeout')}if(options.cancelDuringCharge)subs.rows[1][7]='cancelled';return{getResponseCode:()=>options.status||200,getContentText:()=>JSON.stringify({orderId:p.orderId,totalAmount:19900,status:'DONE',paymentKey:'fake-payment',approvedAt:new Date().toISOString()})}}}};
 vm.createContext(env);vm.runInContext(template,env);return{env,props,calls,subs,licenses,orders,triggers,due,run:()=>env.renewLewordMonthly_('LP-test')};
}
test('new monthly renews same license, then duplicate run skips',()=>{const s=setup();assert.equal(s.run().ok,true);assert.equal(s.subs.rows[1][9],'CODE');assert.ok(new Date(s.licenses.rows[1][5]).getTime()>Date.now());assert.equal(s.run().skipped,true);assert.equal(s.calls.length,1);assert.equal(s.orders.rows.length,2)});
test('license persistence failure leaves due unchanged and retries without recharging',()=>{const s=setup();s.licenses.failOnce=true;assert.equal(s.run().ok,false);assert.equal(s.subs.rows[1][6],s.due);assert.equal(s.run().ok,true);assert.equal(s.calls.length,1)});
test('subscription persistence failure retries same grant and order',()=>{const s=setup();s.subs.failOnce=true;assert.equal(s.run().ok,false);assert.equal(s.run().ok,true);assert.equal(s.calls.length,1);assert.equal(s.orders.rows.length,2)});
test('network retry keeps stable order and idempotency key',()=>{const s=setup({timeoutOnce:true});s.run();assert.equal(s.run().ok,true);assert.equal(s.calls[0].opts.payload,s.calls[1].opts.payload);assert.equal(s.calls[0].opts.headers['Idempotency-Key'],s.calls[1].opts.headers['Idempotency-Key'])});
test('unmarked old and other plan rows never use dedicated renewal',()=>{const s=setup();s.props.clear();assert.equal(s.run().skipped,true);s.props.set('LEWORD_MONTHLY_RECEIPT_LP-test','hash');s.subs.rows[1][5]=30000;assert.equal(s.run().skipped,true);assert.equal(s.calls.length,0)});
test('cancelled subscription cannot charge',()=>{const s=setup();s.subs.rows[1][7]='cancelled';assert.equal(s.run().skipped,true);assert.equal(s.calls.length,0)});
test('concurrent cancellation is preserved while settling payment',()=>{const s=setup({cancelDuringCharge:true});assert.equal(s.run().ok,true);assert.equal(s.subs.rows[1][7],'cancelled')});
test('dedicated trigger installation is idempotent and never creates global trigger',()=>{const s=setup();s.env.ensureLewordMonthlyRenewalTrigger_();s.env.ensureLewordMonthlyRenewalTrigger_();assert.deepEqual(s.triggers,['processLewordMonthlyRenewals'])});
test('three conclusive failures expire new subscription without advancing expiry',()=>{const s=setup({status:400});s.run();s.run();s.run();assert.equal(s.subs.rows[1][7],'expired');assert.equal(s.subs.rows[1][6],s.due);assert.equal(s.orders.rows.length,1)});
test('expired idempotency retry window never sends another charge',()=>{const s=setup({timeoutOnce:true});s.run();for(const [k,v]of s.props)if(k.startsWith('LEWORD_RENEW_'))s.props.set(k,JSON.stringify({...JSON.parse(v),startedAt:new Date(Date.now()-8*86400000).toISOString()}));assert.equal(s.run().ok,false);assert.equal(s.calls.length,1)});
test('concurrent cancellation survives payment decline',()=>{const s=setup({status:400,cancelDuringCharge:true});assert.equal(s.run().ok,false);assert.equal(s.subs.rows[1][7],'cancelled');assert.equal(s.subs.rows[1][8],0)});
test('cancelled subscription still receives an already paid period after grant recovery',()=>{const s=setup();s.licenses.failOnce=true;assert.equal(s.run().ok,false);s.subs.rows[1][7]='cancelled';assert.equal(s.run().ok,true);assert.equal(s.subs.rows[1][7],'cancelled');assert.ok(new Date(s.licenses.rows[1][5]).getTime()>Date.now());assert.equal(s.calls.length,1)});

test('cancel after payment timeout recovers using GET only',()=>{const s=setup({timeoutOnce:true});assert.equal(s.run().ok,false);s.subs.rows[1][7]='cancelled';assert.equal(s.run().ok,true);assert.equal(s.subs.rows[1][7],'cancelled');assert.equal(s.calls.length,2);assert.equal(s.calls[1].opts.method,'get');assert.equal(s.calls.filter(c=>c.opts.method==='post').length,1)});
test('failed read-only settlement lookup after cancellation never charges or grants',()=>{const options={timeoutOnce:true};const s=setup(options);s.run();s.subs.rows[1][7]='cancelled';options.status=404;assert.equal(s.run().ok,false);assert.equal(s.subs.rows[1][6],s.due);assert.equal(s.orders.rows.length,1);assert.equal(s.calls[1].opts.method,'get');assert.equal(s.calls.filter(c=>c.opts.method==='post').length,1)});
