const test=require('node:test'); const assert=require('node:assert/strict'); const vm=require('node:vm');
const template=require('./leword-monthly-billing-template.cjs');
function setup(options={}) {
 const props=new Map(); const calls=[]; let codeSeq=0;
 const sheet=(headers)=>({rows:[headers],getDataRange(){return{getValues:()=>this.rows.map(r=>[...r])}},appendRow(row){if(this.failOnce){this.failOnce=false;throw Error('write unavailable')}this.rows.push([...row])}});
 const subs=sheet(['customerKey','email','billingKey','productId','name','amount','next','status','retry','code']); const licenses=sheet(['code','platform','type','used','customDays']); const orders=sheet(['orderId']);
 const env={Date,JSON,Number,String,Object,Error,Logger:{log(){}},jsonpResponse:(_,data)=>data,LockService:{getScriptLock:()=>({tryLock:()=>!options.locked,releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v),deleteProperty:k=>props.delete(k)})},ensureLewordMonthlyRenewalTrigger_:()=>{if(options.triggerFail)throw Error('trigger unavailable')},getSubscriptionSheet:()=>subs,getSheet:()=>licenses,getOrderSheet:()=>orders,ensureHeaders:s=>s.rows[0],findColumnIndex:(h,k)=>h.indexOf(k)+1,SpreadsheetApp:{flush(){}},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,value)=>Array.from(require('node:crypto').createHash('sha256').update(value).digest()),base64Encode:x=>Buffer.from(x).toString('base64')},getTossSecretKey:()=>'',generateLicenseCode:()=>`CODE-${++codeSeq}`,sendLicenseEmail(){},UrlFetchApp:{fetch(url,opts){calls.push({url,opts}); const request=JSON.parse(opts.payload);if(url.endsWith('/issue')){if(options.issueTimeout)throw Error('timeout');return{getResponseCode:()=>options.issueStatus||200,getContentText:()=>JSON.stringify(options.issueStatus?{code:'INVALID_AUTH'}:{billingKey:'fake-key'})}}if(options.payTimeoutOnce){options.payTimeoutOnce=false;throw Error('timeout')}return{getResponseCode:()=>200,getContentText:()=>JSON.stringify({orderId:request.orderId,totalAmount:options.badAmount?1:19900,status:'DONE',paymentKey:'fake-payment',approvedAt:new Date().toISOString()})}}}};
 vm.createContext(env);vm.runInContext(template,env);return {env,props,calls,subs,licenses,orders,run:p=>env.handleLewordMonthlyBilling_({product:'leword-monthly',amount:19900,email:'buyer@example.test',customerKey:'LP-example-123',authKey:'one-use',...p})};
}
test('requires exact server price before issuing billing key',()=>{const s=setup();assert.equal(s.run({amount:1}).ok,false);assert.equal(s.run({amount:21890}).ok,false);assert.equal(s.calls.length,0)});
test('requires valid identity before external calls',()=>{const s=setup();assert.equal(s.run({email:'invalid'}).ok,false);assert.equal(s.run({customerKey:'../../x'}).ok,false);assert.equal(s.calls.length,0)});
test('charges 19900 and grants LEWORD 30 days',()=>{const s=setup();const r=s.run();assert.equal(r.ok,true);assert.equal(JSON.parse(s.calls[1].opts.payload).amount,19900);assert.deepEqual(s.licenses.rows[1],['CODE-1','LEWORD','CUSTOM',false,30]);assert.equal(s.subs.rows[1][5],19900);assert.equal(s.orders.rows.length,2);assert.ok(r.nextPaymentDate);assert.equal(s.props.size,1)});
test('same customer key is idempotent after success',()=>{const s=setup();const first=s.run();const again=s.run();assert.equal(again.code,first.code);assert.equal(again.reused,true);assert.equal(s.calls.length,2);assert.equal(s.subs.rows.length,2)});
test('blocks changed email and duplicate active monthly subscription',()=>{const s=setup();s.run();assert.equal(s.run({email:'other@example.test'}).ok,false);assert.equal(s.run({customerKey:'other-attempt'}).ok,false);assert.equal(s.calls.length,2)});
test('ambiguous billing-key issuance never retries one-use auth',()=>{const s=setup({issueTimeout:true});assert.equal(s.run().ok,false);assert.equal(s.run().ok,false);assert.equal(s.calls.length,1)});
test('payment timeout retries same billing key and same idempotency key',()=>{const s=setup({payTimeoutOnce:true});assert.equal(s.run().ok,false);assert.equal(s.run().ok,true);assert.equal(s.calls.filter(c=>c.url.endsWith('/issue')).length,1);assert.equal(s.calls[1].opts.headers['Idempotency-Key'],s.calls[2].opts.headers['Idempotency-Key']);assert.equal(s.calls[1].opts.payload,s.calls[2].opts.payload)});
test('subscription save failure retries persistence without charging twice',()=>{const s=setup();s.subs.failOnce=true;assert.equal(s.run().ok,false);assert.equal(s.run().ok,true);assert.equal(s.calls.length,2);assert.equal(s.licenses.rows.length,2);assert.equal(s.orders.rows.length,2);assert.equal(s.subs.rows.length,2)});
test('license save failure does not falsely report success',()=>{const s=setup();s.licenses.failOnce=true;assert.equal(s.run().ok,false);assert.equal(s.subs.rows.length,1);assert.equal(s.run().ok,true);assert.equal(s.calls.length,2)});
test('unexpected amount from payment API never grants access',()=>{const s=setup({badAmount:true});assert.equal(s.run().ok,false);assert.equal(s.subs.rows.length,1);assert.equal(s.licenses.rows.length,1)});
test('lock prevents concurrent payment execution',()=>{const s=setup({locked:true});assert.equal(s.run().ok,false);assert.equal(s.calls.length,0)});
test('manual-bank mapping is monthly LEWORD only; tampered label/amount rejected',()=>{const s=setup();const f=s.env.lewordMonthlyBankInfo_;assert.equal(f('LEWORD 1개월',19900).platform,'LEWORD');assert.equal(f('LEWORD 1개월',19900).customDays,30);assert.throws(()=>f('LEWORD 1개월',1));assert.throws(()=>f('올인원 1년',19900));assert.equal(f('올인원 1개월',50000),null)});

test('receipt replay requires original auth binding',()=>{const s=setup();s.run();assert.equal(s.run({authKey:'guessed'}).ok,false);assert.equal(s.calls.length,2)});
test('unfinished payment blocks a new customerKey with the same email',()=>{const s=setup();s.subs.failOnce=true;assert.equal(s.run().ok,false);assert.equal(s.run({customerKey:'new-attempt',authKey:'new-auth'}).ok,false);assert.equal(s.calls.length,2);assert.equal(s.run().ok,true)});
test('pending state cannot be retried with different auth key',()=>{const s=setup({payTimeoutOnce:true});s.run();assert.equal(s.run({authKey:'different'}).ok,false);assert.equal(s.calls.length,2)});

test('conclusive authorization rejection clears pending email lock',()=>{const options={issueStatus:400};const s=setup(options);assert.equal(s.run().ok,false);assert.equal(s.props.size,0);options.issueStatus=undefined;assert.equal(s.run({customerKey:'new-attempt',authKey:'new-auth'}).ok,true)});

test('trigger installation failure stops before card authorization or payment',()=>{const s=setup({triggerFail:true});assert.equal(s.run().ok,false);assert.equal(s.calls.length,0)});
test('managed receipt marker is persisted before subscription row',()=>{const s=setup();s.subs.failOnce=true;s.run();assert.ok(s.props.has('LEWORD_MONTHLY_RECEIPT_LP-example-123'));assert.equal(s.subs.rows.length,1)});
test('completed-row retry recovers pending state cleanup',()=>{const s=setup();s.run();const authHash=s.props.get('LEWORD_MONTHLY_RECEIPT_LP-example-123');const emailHash=require('node:crypto').createHash('sha256').update('buyer@example.test').digest('base64');s.props.set('LEWORD_MONTHLY_LP-example-123',JSON.stringify({email:'buyer@example.test',authHash}));s.props.set('LEWORD_MONTHLY_PENDING_'+emailHash,'LP-example-123');assert.equal(s.run().ok,true);assert.equal(s.props.size,1);assert.equal(s.calls.length,2)});
test('new manual orders reject both known historical monthly prices',()=>{const f=setup().env.lewordMonthlyBankInfo_;for(const amount of [9900,30000])assert.throws(()=>f('LEWORD 1개월',amount))});
test('approval alone can honor known historical LEWORD monthly orders',()=>{const f=setup().env.lewordMonthlyBankInfo_;for(const amount of [9900,30000]){const info=f('LEWORD 1개월',amount,true);assert.equal(info.platform,'LEWORD');assert.equal(info.customDays,30);assert.equal(info.licenseType,'CUSTOM')}assert.throws(()=>f('LEWORD 1개월',10000,true))});
test('legacy approval flag cannot grant LEWORD to unrelated labels',()=>{const f=setup().env.lewordMonthlyBankInfo_;for(const label of ['올인원 1개월','LEWORD 1년','LEWORD + Orbit 1개월'])for(const amount of [9900,30000])assert.equal(f(label,amount,true),null)});
